BlowOut/Models/Client.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BlowOut.Models
{
    [Table("Clients")]
    public class Client
    {
        [Key]
        public int ClientID { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public String Address { get; set; }
        public String City { get; set; }
        public String State { get; set; }
        public String Zip { get; set; }
        public String Email { get; set; }
        public String Phone { get; set; }
       
    }
}

BlowOut/Models/ClientRental.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BlowOut.Models
{
    public class ClientRental
    {
        [Key]
        public int ClientID { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public String Address { get; set; }
        public String City { get; set; }
        public String State { get; set; }
        public String Zip { get; set; }
        public String Email { get; set; }
        public String Phone { get; set; }

        [DisplayName("Instrument:")]
        public string InstrumentType { get; set; }

        [Required(ErrorMessage = "Please select rental type")]
        [DisplayName("Rental Type:")]
        public string NewOrUsed { get; set; }

        [DisplayName("Price:")]
        public int InstrumentPrice { get; set; }
    }
}

BlowOut/Models/Gmail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlowOut.Models
{
    public class Gmail
    {
        public string to { get; set; }
        public string from { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
    }
}

BlowOut/Models/Instrument.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BlowOut.Models
{
    [Table("Instruments")]
    public class Instrument
    {
        [Key]
        public int InstID { get; set; }
        public string InstDesc { get; set; }
        public string InstType { get; set; }
        public int InstPrice { get; set; }
        public int ClientID { get; set; }
    }
}

BlowOut/Models/InstrumentType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlowOut.Models
{
    public class InstrumentType
    {
        public static List<InstrumentType> Types = new List<InstrumentType>
        {
            new InstrumentType{Name = "Trumpet", NewPrice = 55, UsedPrice = 25, Picture = "trumpet"},
            new InstrumentType{Name = "Trombone", NewPrice = 60, UsedPrice = 35, Picture = "trombone"},
            new InstrumentType{Name = "Tuba", NewPrice = 70, UsedPrice = 50, Picture = "tuba"},
            new InstrumentType{Name = "Flute", NewPrice = 40, UsedPrice = 25, Picture = "flute"},
            new InstrumentType{Name = "Clarinet", NewPrice = 35, UsedPrice = 27, Picture = "clarinet"},
            new InstrumentType{Name = "Saxophone", NewPrice = 42, UsedPrice = 30, Picture = "saxophone"}
        };

        public int InstrumentTypeID
        public string Name { get; set; }
        public int NewPrice { get; set; }
        public int UsedPrice { get; set; }
        public string Picture { get; set; }
    }
}

BlowOut/Models/Rental.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BlowOut.Models
{
    public class Rental
    {
        [DisplayName("Instrument:")]
        public string InstrumentType { get; set; }

        [Required(ErrorMessage = "Please select rental type")]
        [DisplayName("Rental Type:")]
        public string NewOrUsed { get; set; }

        [DisplayName("Price:")]
        public int InstrumentPrice { get; set; }

    }
}

BlowOut/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlowOut.Controllers
{
    public class ClientController : Controller
    {
        // GET: Client
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddClient()
        {

            return View();
        }
    }
}

BlowOut/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlowOut.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Email(string name, string email)
        {
            ViewBag.eMessage = "Thank you, " + name + "! The company will send an email to " + email; 
            return View();
        }


    }
}

BlowOut/Controllers/EmailSetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlowOut.Models;
using System.Net;
using System.Net.Mail;


namespace BlowOut.Controllers
{
    public class EmailSetupController : Controller
    {
        // GET: EmailSetup
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(BlowOut.Models.Gmail model)
        {
            MailMessage mm = new MailMessage("keara.hutchinson@gmail.com", model.to);
            mm.Subject = model.subject;
            mm.Body = model.body;
            mm.IsBodyHtml = false;

            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.Port = 587;
            smtp.EnableSsl = true;

            NetworkCredential nc = new NetworkCredential("keara.hutchinson@gmail.com", "KearaD58");
            smtp.UseDefaultCredentials = true;
            smtp.Credentials = nc;
            smtp.Send(mm);

            ViewBag.message = "Mail has been sent successfully";

            return View();
        }
    }
}

BlowOut/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//GROUP 2-1
//KEARA HUTCHINSON, DAVID KNIGHT, NATHAN HANSEN, HAYLEY MYERS
//THIS PROGRAM SHOWS THE PRICES OF INSTRUMENTS
namespace BlowOut.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BlowOut/Controllers/RentalController.cs
using BlowOut.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlowOut.Controllers
{
    public class RentalController : Controller
    {
        public ActionResult Rentals()
        {
            return View();
        }

        public ActionResult ListRentals()
        {
            return View(InstrumentType.Types);
        }

        public ActionResult NewRental(string InstrumentName)
        {
            ViewBag.InstrumentName = InstrumentName;
            ViewBag.InstrumentImage = Instrument.InstrumentPictures[InstrumentName];
            ViewBag.NewPrice = Instrument.NewPrices[InstrumentName];
            ViewBag.UsedPrice = Instrument.UsedPrices[InstrumentName];
            return View();
        }
    }
}

BlowOut/Views/Client/AddClient.cshtml
@model BlowOut.Models.ClientRental

@{
    ViewBag.Title = "AddClient";
}

<h2>AddClient</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ClientRental</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InstrumentType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InstrumentPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InstrumentType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NewOrUsed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewOrUsed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewOrUsed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InstrumentPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InstrumentPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InstrumentPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BlowOut/Views/Contact/Email.cshtml
@{
    ViewBag.Title = "Email";
}

<h2>Email</h2>

@Html.Raw(ViewBag.eMessage)

BlowOut/Views/Contact/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>"Please call Support at <u><strong>801-555-1212.</strong></u> Thank you!" </h2>

BlowOut/Views/EmailSetup/Index.cshtml
@model BlowOut.Models.Gmail

@{
    ViewBag.Title = "Index";
}

<h2>Email</h2>

<div>
    @using (Html.BeginForm("Index", "EmailSetup", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <table>
            <tbody>
                <tr>
                    <td style="width: 80px"> </td>
                    To:
                    <td>@Html.TextBoxFor(model=>model.to)</td>
                </tr>
                <tr>
                    <td> Subject: </td>
                    <td>@Html.TextBoxFor(model => model.subject)</td>
                </tr>
                <tr>
                    <td valign="Top"> </td>
                    Body:
                    <td>@Html.TextBoxFor(model => model.body, new { rows = "15", cols="25" })</td>
                </tr>
                <tr>
                    <td> <input type="submit" value="send" /> </td>
                </tr>
            </tbody>
        </table>
        <br />
        <span>@ViewBag.Message </span>

    }
</div>

BlowOut/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BlowOut/Views/Home/Clarinet.cshtml
@{
    ViewBag.Title = "Clarinet";
}
<link href="~/Content/Styles.css" rel="stylesheet" />
<h2>Clarinet</h2>
<img class="viewpic" src="~/Content/Images/clarinet.jpg" />

<button class="myButton" id="new" onmouseover="NewPrice()" onclick="location.href='@Url.Action("AddClient", "Client")'">New</button>

<button class="myButton" id="used" onmouseover="UsedPrice()" onclick="location.href='@Url.Action("AddClient", "Client")'">Used</button>

<p class="price" id="price"></p>


<script>

    function NewPrice()
    {
        document.getElementById("price").innerHTML = "$" + '@Html.Raw(ViewBag.NewPrice)';
    }

      function UsedPrice()
    {
        document.getElementById("price").innerHTML = "$" + '@Html.Raw(ViewBag.UsedPrice)';
    }

</script>

BlowOut/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BlowOut/Views/Home/Flute.cshtml
@{
    ViewBag.Title = "Flute";
}
<link href="~/Content/Styles.css" rel="stylesheet" />
<h2>Flute</h2>
<img class="viewpic" src="~/Content/Images/flute.jpg" />

<button class="myButton" id="new" onmouseover="NewPrice()" onclick="location.href='@Url.Action("AddClient", "Client")'">New</button>

<button class="myButton" id="used" onmouseover="UsedPrice()" onclick="location.href='@Url.Action("AddClient", "Client")'">Used</button>

<p class="price" id="price"></p>


<script>

    function NewPrice()
    {
        document.getElementById("price").innerHTML = "$" + '@Html.Raw(ViewBag.NewPrice)';
    }

      function UsedPrice()
    {
        document.getElementById("price").innerHTML = "$" + '@Html.Raw(ViewBag.UsedPrice)';
    }

</script>

BlowOut/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Blow Out";
}

<link href="~/Content/Styles.css" rel="stylesheet" />
<div style="background:grey" class="jumbotron">
    <h1>Welcome to Blow Out.</h1>
    <p class="lead">We blow our competitors out of the water.</p>
    <p><a href=@Url.Action("Rentals", "Rental") class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<center>
    <img src="~/Content/Images/instruments2.PNG" style="width: 1140px" />
    <div class="row">
        <div class="col-md-6">
            <h2>Services</h2>
            <p>We provide rentals for an arrangemnt of various instruments. You can rent new or used instruments based on your professional or individual needs.</p>
        </div>
        <div class="col-md-6">
            <h2>Testimonial</h2>
            <p>
                "I like songs with trumpets in them." -Keara Hutchinson
            </p>
        </div>
        

    </div>
</center>

BlowOut/Views/Home/Saxophone.cshtml
@{
    ViewBag.Title = "Saxophone";
}
<link href="~/Content/Styles.css" rel="stylesheet" />
<h2>Saxophone</h2>
<img class="viewpic" src="~/Content/Images/saxophone.jpg" />

<button class="myButton" id="new" onmouseover="NewPrice()" onclick="location.href='@Url.Action("AddClient", "Client")'">New</button>

<button class="myButton" id="used" onmouseover="UsedPrice()" onclick="location.href='@Url.Action("AddClient", "Client")'">Used</button>

<p class="price" id="price"></p>


<script>

    function NewPrice()
    {
        document.getElementById("price").innerHTML = "$" + '@Html.Raw(ViewBag.NewPrice)';
    }

      function UsedPrice()
    {
        document.getElementById("price").innerHTML = "$" + '@Html.Raw(ViewBag.UsedPrice)';
    }

</script>

BlowOut/Views/Home/Trombone.cshtml
@{
    ViewBag.Title = "Trombone";
}
<link href="~/Content/Styles.css" rel="stylesheet" />

<h2>Trombone</h2>
<img class="viewpic" src="~/Content/Images/trombone.jpg" />

<button class="myButton" id="new" onmouseover="NewPrice()" onclick="location.href='@Url.Action("AddClient", "Client")'">New</button>

<button class="myButton" id="used" onmouseover="UsedPrice()" onclick="location.href='@Url.Action("AddClient", "Client")'">Used</button>
<p class="price" id="price"></p>



<script>

    function NewPrice()
    {
        document.getElementById("price").innerHTML = "$" + '@Html.Raw(ViewBag.NewPrice)';
    }

      function UsedPrice()
    {
        document.getElementById("price").innerHTML = "$" + '@Html.Raw(ViewBag.UsedPrice)';
    }

</script>

BlowOut/Views/Home/Trumpet.cshtml
@{
    ViewBag.Title = "Trumpet";
}
<link href="~/Content/Styles.css" rel="stylesheet" />


<h2>Trumpet</h2>
<img class="viewpic" src="~/Content/Images/trumpet.jpg" />


<button class="myButton" id="new" onmouseover="NewPrice()" onclick="location.href='@Url.Action("AddClient", "Client")'">New</button>

<button class="myButton" id="used" onmouseover="UsedPrice()" onclick="location.href='@Url.Action("AddClient", "Client")'">Used</button>
<p class="price" id="price"></p>


<script>

    function NewPrice()
    {
        document.getElementById("price").innerHTML = "$" + '@Html.Raw(ViewBag.NewPrice)';
    }

      function UsedPrice()
    {
        document.getElementById("price").innerHTML = "$" + '@Html.Raw(ViewBag.UsedPrice)';
    }

</script>

BlowOut/Views/Home/Tuba.cshtml
@{
    ViewBag.Title = "Tuba";
}
<link href="~/Content/Styles.css" rel="stylesheet" />
<h2>Tuba</h2>
<img class="viewpic" src="~/Content/Images/tuba.jpg" />

<button class="myButton" id="new" onmouseover="NewPrice()" onclick="location.href='@Url.Action("AddClient", "Client")'">New</button>

<button class="myButton" id="used" onmouseover="UsedPrice()" onclick="location.href='@Url.Action("AddClient", "Client")'">Used</button>

<p class="price" id="price"></p>


<script>

    function NewPrice()
    {
        document.getElementById("price").innerHTML = "$" + '@Html.Raw(ViewBag.NewPrice)';
    }

      function UsedPrice()
    {
        document.getElementById("price").innerHTML = "$" + '@Html.Raw(ViewBag.UsedPrice)';
    }

</script>

BlowOut/Views/Rental/ListRentals.cshtml
@model List<BlowOut.Models.InstrumentType>

@{
    ViewBag.Title = "ListRentals";
}

<h2>ListRentals</h2>

<table class="table">
    @for(int i = 0; i < this.Model.Count(); i += 3)
 //       (var item in Model)
    {
    <tr>
        <td>
            <a href="@Url.Action("NewRental", new { InstrumentName = this.Model[i].Name })">
                <img height="200" width="190" src="~/Content/Images/@(this.Model[i].Picture).jpg" />
            </a>
            <br />
            <p>@(this.Model[i].Name)</p>
        </td>
        @if (i + 1 < this.Model.Count())
        {
            <td>
                <a href="@Url.Action("NewRental", new { InstrumentName = this.Model[i+1].Name })">
                    <img height="200" width="190" src="~/Content/Images/@(this.Model[i+1].Picture).jpg" />
                </a>
                <br />
                <p>@(this.Model[i+1].Name)</p>
            </td>
        }
        @if (i + 2 < this.Model.Count())
        {
            <td>
                <a href="@Url.Action("NewRental", new { InstrumentName = this.Model[i+2].Name })">
                    <img height="200" width="190" src="~/Content/Images/@(this.Model[i+2].Picture).jpg" />
                </a>
                <br />
                <p>@(this.Model[i+2].Name)</p>
            </td>
        }
    </tr>
    }

</table>

BlowOut/Views/Rental/NewRental.cshtml
@{
    ViewBag.Title = ViewBag.InstrumentName;
}

<link href="~/Content/Styles.css" rel="stylesheet" />
<h2>@Html.Raw(ViewBag.InstrumentName)</h2>
<img class="viewpic" src="~/Content/Images/@(ViewBag.InstrumentName).jpg"/>
<select id="NewUsed" onchange="Price(this.value)">
    <option value=""></option>
    <option value="New">New</option>
    <option value="Used">Used</option>
</select>
<p class="price" id="price"></p>


<script>

    function Price(NewOrUsed)
    {
        if (NewOrUsed == "New") {
            document.getElementById("price").innerHTML = "$" + '@Html.Raw(ViewBag.NewPrice)';
        }
        else if (NewOrUsed == "Used") {
            document.getElementById("price").innerHTML = "$" + '@Html.Raw(ViewBag.UsedPrice)';
        }
        else {
            document.getElementById("price").innerHTML = "";
        }
        console.log(NewOrUsed);
    }

</script>

BlowOut/Views/Rental/Rentals.cshtml
@{
    ViewBag.Title = "Rentals";
}

<link href="~/Content/Styles.css" rel="stylesheet" />
<h2 class="rentalstitle ">RENTALS</h2>
<div>
    <div>
        <a href="@Url.Action("NewRental", new { InstrumentName = "Trumpet" })">
            <img class="picture1" src="~/Content/Images/trumpet.jpg" />
        </a>
        <p class="text1">Trumpets</p>
    </div>
    <div>
        <a href="@Url.Action("NewRental", new { InstrumentName = "Trombone" })">
            <img class="picture2" src="~/Content/Images/trombone.jpg" />
        </a>
        <p class="text2">Trombones</p>
    </div>
    <div>
        <a href="@Url.Action("NewRental", new { InstrumentName = "Trumpet" })">
            <img class="picture3" src="~/Content/Images/tuba.jpg" />
        </a>
        <p class="text3">Tubas</p>
    </div>
    <div>
        <a href="@Url.Action("NewRental", new { InstrumentName = "Trumpet" })">
            <img class="picture4" src="~/Content/Images/flute.jpg" />
        </a>
        <p class="text4">Flutes</p>
    </div>
    <div>
        <a href="@Url.Action("NewRental", new { InstrumentName = "Trumpet" })">
            <img class="picture5" src="~/Content/Images/clarinet.jpg" />
        </a>
        <p class="text5">Clarinets</p>
    </div>
    <div>
        <a href="@Url.Action("NewRental", new { InstrumentName = "Trumpet" })">
            <img class="picture6" src="~/Content/Images/saxophone.jpg" />
        </a>
        <p class="text6">Saxophones</p>
    </div>
</div>

BlowOut/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BlowOut Musical Instrument Rentals</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BlowOut Instrument Rentals", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Rentals", "Rentals", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    @RenderBody()

    <div class="container body-content">
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Blow Out Rentals</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>